### ISSUE TITLE
why two Markovian discriminators are used？

### ISSUE THREAD

**Issue by nachifur** [jiupinjia/Deep-adversarial-decomposition#4]
This work is very meaningful. 
I don't know why two discriminators are used here. Will the performance of one discriminator decrease? I did not find relevant experiments and discussions in the article.
I will appreciate any reply from you.
![DeepinScreenshot_select-area_20201021132554](https://user-images.githubusercontent.com/23144348/96677094-747ddc80-13a1-11eb-99c1-f776ac2cc440.png)

**Comment by jiupinjia** [comment]
> This work is very meaningful.
> I don't know why two discriminators are used here. Will the performance of one discriminator decrease? I did not find relevant experiments and discussions in the article.
> I will appreciate any reply from you.

Very good question. In our preliminary experiments, we found the double-discriminator configuration may slightly improve the separation than using a single one. This could be particularly happening when the two mixture components are from different domains (e.g, dogs + flowers) since the double-discriminator helps to learn the respective distribution of the two domains. When the mixture is from a single domain (e.g., dogs + dogs) we believe the single-discriminator and double-discriminator could have similar performance although we didn't verify it. Thank you!

**Comment by nachifur** [comment]
Thank you for your reply.
